apiVersion: v1
kind: Pod
metadata:
  name: too-big
  labels: { app: too-big }
spec:
  containers:
  - name: app
    image: busybox:1.36
    command: ["sh","-c","sleep 3600"]
    resources:
      requests:
        cpu: "100m"
        memory: "32Gi"     # Intentionally larger than a single-node lab
      limits:
        memory: "32Gi"
